apiVersion: v1
kind: Service
metadata:
  name: cashflow-api
  namespace: arch-challenge
  labels:
    app.kubernetes.io/name: cashflow-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cashflow-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cashflow-api
  ports:
    - name: http
      port: 80
      targetPort: http
