apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: arch-challenge
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: cashflow-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
