apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cashflow-api
  namespace: arch-challenge
  labels:
    app.kubernetes.io/name: cashflow-api
    app.kubernetes.io/part-of: cashflow-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cashflow-api
