apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arch-challenge

resources:
  - namespace.yaml
  - configmap.yaml
  - cashflow-deployment.yaml
  - cashflow-service.yaml
  - cashflow-pdb.yaml
  - cashflow-hpa.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - gateway-pdb.yaml
  - ingress.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
