version: '3.8'
services:
  entries-api:
    build:
      context: .
      dockerfile: Entries/CashFlow.Entries.API/Dockerfile
    ports:
      - "5001:8080"
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis

  daily-consolidated-api:
    build:
      context: .
      dockerfile: DailyConsolidated/CashFlow.DailyConsolidated.API/Dockerfile
    ports:
      - "5003:8080"
      - "5004:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: