CREATE DATABASE EntriesDataBase;
GO

USE EntriesDataBase
GO

/****** Object:  Table [dbo].[TB_ENTRY]    Script Date: 26/04/2025 10:26:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_ENTRY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[VALUE] [decimal](18, 2) NULL,
	[DATEENTRY] [datetime] NULL,
	[ISCREDIT] [bit] NULL,
 CONSTRAINT [PK_TB_ENTRY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TB_USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL] [varchar](100) NULL,
	[SENHA] [varchar](50) NULL,
 CONSTRAINT [PK_TB_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TB_LOGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[DATA] [datetime] NULL,
 CONSTRAINT [PK_TB_LOGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_LOGS]  WITH CHECK ADD  CONSTRAINT [FK_TB_LOGS_TB_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TB_USUARIO] ([ID])
GO

ALTER TABLE [dbo].[TB_LOGS] CHECK CONSTRAINT [FK_TB_LOGS_TB_USUARIO]
GO

CREATE TABLE [dbo].[TB_USUARIO_CTRL_ACESSO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LAST_ACCESS] [datetime] NULL,
	[TRY_NUMBER] [int] NULL,
	[BLOCKED] [bit] NULL,
	[USER_EMAIL] [varchar](100) NULL,
 CONSTRAINT [PK_TB_USUARIO_CTRL_ACESSO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO [dbo].[TB_USUARIO]
           ([EMAIL]
           ,[SENHA])
     VALUES
           ('teste@teste.com.br','senha123');