// <auto-generated />
using System;
using ArchChallenge.CashFlow.Infrastructure.Data.Relational.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchChallenge.CashFlow.Infrastructure.Data.Relational.Migrations
{
    [DbContext(typeof(CashFlowDbContext))]
    partial class CashFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_ACTIVE");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VL_AMOUNT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("DS_TRANSACTION");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("ST_TYPE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("TB_TRANSACTION", (string)null);
                });

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Shared.Events.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DS_EVENT_TYPE");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DS_PAYLOAD");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_PROCESSED");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_PROCESSED_AT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("NR_RETRY_COUNT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Processed", "CreatedAt")
                        .HasDatabaseName("IX_AUDIT_OUTBOX_EVENT_PROCESSED_CREATED");

                    b.ToTable("TB_OUTBOX_AUDIT_EVENT", "outbox");
                });

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Shared.Events.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DS_EVENT_TYPE");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DS_PAYLOAD");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_PROCESSED");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_PROCESSED_AT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("NR_RETRY_COUNT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Processed", "CreatedAt")
                        .HasDatabaseName("IX_OUTBOX_EVENT_PROCESSED_CREATED");

                    b.ToTable("TB_OUTBOX_EVENT", "outbox");
                });
#pragma warning restore 612, 618
        }
    }
}
