// <auto-generated />
using System;
using FluxoCaixa.Consolidado.Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxoCaixa.Consolidado.Api.Persistencia.Migracoes
{
    [DbContext(typeof(ConsolidadoDbContext))]
    partial class ConsolidadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixa.Consolidado.Api.Persistencia.ConsolidadoDiario", b =>
                {
                    b.Property<string>("ComercianteId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("comerciante_id");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date")
                        .HasColumnName("competencia");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<decimal>("TotalCredito")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_credito");

                    b.Property<decimal>("TotalDebito")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debito");

                    b.HasKey("ComercianteId", "Competencia");

                    b.ToTable("consolidado_diario", (string)null);
                });

            modelBuilder.Entity("FluxoCaixa.Consolidado.Api.Persistencia.LancamentoProcessado", b =>
                {
                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("ComercianteId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("comerciante_id");

                    b.Property<DateTimeOffset>("ProcessadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processado_em");

                    b.HasKey("LancamentoId");

                    b.HasIndex("ProcessadoEm")
                        .HasDatabaseName("ix_lancamento_processado_processado_em");

                    b.ToTable("lancamento_processado", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
