services:
  postgres_transactions:
    image: postgres:17
    container_name: postgres_transactions
    restart: always
    environment:
      POSTGRES_DB: verity_transactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - verity_network
    volumes:
      - postgres_transactions_data:/var/lib/postgresql/data

  postgres_daily_summary:
    image: postgres:17
    container_name: postgres_daily_summary
    restart: always
    environment:
      POSTGRES_DB: verity_daily_summary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    networks:
      - verity_network
    volumes:
      - postgres_daily_summary_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - verity_network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - verity_network

networks:
  verity_network:
    driver: bridge

volumes:
  postgres_transactions_data:
  postgres_daily_summary_data: