FROM prom/prometheus:latest

USER root

# Instala tzdata e configura fuso horário para São Paulo
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    echo "America/Sao_Paulo" > /etc/timezone

USER nobody
