server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["localhost"]
        labels:
          job: api
          __path__: /app/logs-fallback/log-*.json
