receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['localhost:8888']

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheus]
