global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    
  - job_name: 'fluxocaixa-lancamento'
    static_configs:
      - targets: ['host.docker.internal:60280']
    metrics_path: /metrics
    scrape_interval: 10s
    
  - job_name: 'fluxocaixa-consolidado'
    static_configs:
      - targets: ['host.docker.internal:60281']
    metrics_path: /metrics
    scrape_interval: 10s