services:
  lancamentos-api:
    build: 
      context: .
      dockerfile: src/Services/FluxoCaixa.Lancamentos/Dockerfile
    ports: 
      - "5001:8080"
    depends_on: 
      - sqlserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FluxoCaixaLancamentos;User Id=sa;Password=SuaSenha@123;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest

  consolidado-api:
    build: 
      context: .
      dockerfile: src/Services/FluxoCaixa.Consolidado/Dockerfile
    ports: 
      - "5002:8080"
    depends_on: 
      - sqlserver
      - rabbitmq
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FluxoCaixaConsolidado;User Id=sa;Password=SuaSenha@123;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - Redis__ConnectionString=redis:6379

  gateway:
    build: 
      context: .
      dockerfile: src/Gateway/FluxoCaixa.Gateway/Dockerfile
    ports: 
      - "5000:8080"
    depends_on: 
      - lancamentos-api
      - consolidado-api
    environment:
      - ReverseProxy__Clusters__lancamentosCluster__Destinations__destination1__Address=http://lancamentos-api:8080
      - ReverseProxy__Clusters__consolidadoCluster__Destinations__destination1__Address=http://consolidado-api:8080

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuaSenha@123"
    ports: 
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"

volumes:
  sqlserver_data:
